language: python
python:
  - "pypy"
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install coveralls
script:
  - coverage run --source=jsonmerge setup.py test
after_success:
  - coveralls
